### ISSUE TITLE
Demo requires Postgres database

### ISSUE THREAD

**Issue by zolrath** [BartOtten/phoenix_live_favicon_example#1]
### Problem
The demo itself doesn't use any Ecto/Postgres features, but still requires a Postgres database.

### Solution
Moving the demo to use a `--no-ecto` Phoenix template as its base would make quickly running it without needing to spin up a new Postgres container or database quite a bit easier.

Alternatively, swapping from Postgres to the SQLite adapter would allow you to keep Ecto, if you plan on providing examples that require it.

**Comment by BartOtten** [comment]
Thank you for taking the time to point this out. I have removed the need for a database in https://github.com/BartOtten/phoenix_live_favicon_example/commit/dffa7d7c433988b96bb14533e5c988ccc58df683
